name: Yotta Demoday Deploy

on:
  push:
    branches: [master]
    paths:
      - "app/**"
      - "bootstrap/**"
      - "config/**"
      - "database/**"
      - "resources/**"
      - "routes/**"
      - "storage/**"
      - "test/**"
      - ".editorconfig"
      - ".env.example"
      - ".gitattributes"
      - ".gitignore"
      - "artisan"
      - "composer.json"
      - "composer.lock"
      - "package.json"
      - "phpunit.xml"
      - "README.md"
      - "vite.config.js"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.3.4
        with:
          server: "ftp://${{ secrets.FTP_SERVER }}:65002"
          username: "${{ secrets.FTP_USERNAME }}"
          password: "${{ secrets.FTP_PASSWORD }}"
          server-dir: "/domains/demoday.aksarayotta.com/public_html/"
